package: mediaplace
version: '1.3.10'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO

page:
    title: 'MediaPlace'
    icon: rex-icon fa-photo-film
    perm: admin
    subpages:
        settings:
            title: 'Einstellungen'
            icon: rex-icon fa-gear
            perm: admin
        metainfo_fields:
            title: 'Metainfo Felder'
            icon: rex-icon fa-sliders
            perm: admin
        demo:
            title: 'Demo'
            icon: rex-icon fa-play
            perm: admin
        help:
            title: 'translate:help'
            subPath: README.md
            itemClass: 'pull-right'
            perm: admin

requires:
    redaxo: '>=5.20'
    php:
        version: '>=8.4'
    packages:
        api: '>=1.3'
        mediapool: '^2.13.0'

default_config:
    replace_classic_mediapool: true
    enable_own_metadata: false
    disable_tagging: false
    disable_collections: false
    enable_metainfo_editing: false
    enable_upload_resize: false
    upload_resize_width: 2000
    upload_resize_height: 2000
